model:
  path: "/home/god/jetson-yolo-realsense-kuka/models/yolov8n.pt"
  conf_threshold: 0.25
  iou_threshold: 0.45
  classes: []  # empty means all classes

runtime:
  device: "auto"  # "auto", "cpu", or CUDA index e.g. "0"
  half: true       # use FP16 when on CUDA
  visualize: false
  draw: true
  max_fps: 30
  mode: "single"   # "realtime" or "single"
  warmup_frames: 3    # used when mode == "single"

camera:
  serial: ""       # empty for first available
  color:
    width: 640
    height: 480
    fps: 30
  depth:
    width: 640
    height: 480
    fps: 30
  align_to_color: true

output:
  udp:
    enabled: true
    host: "127.0.0.1"
    port: 5005
    send_depth_xyz: true
    max_detections: 20
  preview_window: true
  tcp:
    enabled: false
    host: "127.0.0.1"
    port: 6000
    newline: true
  eki:
    enabled: false
    host: "127.0.0.1"
    port: 7000
    only_first_detection: true
    use_robot_xyz: true
    root_tag: "EKI"
    pretty: false

logging:
  level: "INFO"
  file: "/home/god/jetson-yolo-realsense-kuka/run.log"

calibration:
  # 4x4 homogeneous transform from camera frame to robot base frame
  # identity by default; replace with your calibrated matrix
  T_cam_to_robot:
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]


